spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/aistudyhub
    username: ${DATABASE_USERNAME:dev}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      max-lifetime: 300000
      idle-timeout: 60000
      validation-timeout: 5000
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Giúp sql dễ đọc hơn
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # CÁI NÀY LÀ KEY: Show giá trị thực truyền vào câu query
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  mvc:
    log-request-details: true # Cho phép log chi tiết thông tin request

logging:
  level:
    root: INFO
    # Log toàn bộ request/response tới controller
    vn.ai_study_hub_api: DEBUG
    # Log chi tiết các thao tác của hibernate
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG
    # Log chi tiết header/body request của Spring Web
    org.springframework.web: DEBUG