server:
  port: 8080

spring:
  application:
    name: ai-study-hub-api
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:4300/auth/google/callback}"
            scope:
              - email
              - profile
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  mail:
    host: smtp.gmail.com
    port: 587
    username: tanhai21052005@gmail.com
    password: kqxq masa xgam mals
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    url: jdbc:postgresql://localhost:5432/ai_study_hub
    username: postgres
    password: your_password
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000


  mail:
    host: smtp.gmail.com
    port: 587
    username: tanhai21052005@gmail.com
    password: kqxq masa xgam mals
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO
    vn.ai_study_hub_api: DEBUG # Thêm dòng này để log ra các bước xử lý của bạn
app:
  jwt:
    secret: ${JWT_SECRET:9a4f2c8d3e7b1a5c6d8e0f9b8c7a6d5e4f3c2b1a0d9e8f7a6b5c4d3e2f1a0b9c}
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000